from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
from typing import Iterable


PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = PROJECT_ROOT / "config"
CONFIG_LOCAL_DIR = CONFIG_DIR / "local"
CONFIG_TEMPLATE_DIR = CONFIG_DIR / "templates"
RUNTIME_DIR = PROJECT_ROOT / "runtime"
RUNTIME_ENV_FILE = CONFIG_LOCAL_DIR / "runtime.env"
INSTALLATION_MARKER_FILE = RUNTIME_DIR / "installation.json"
DEFAULT_PROMPT_FILE = PROJECT_ROOT / "英语二的备考prompt.txt"
DEFAULT_WEB_PORT = 8031
DEFAULT_ANKI_CONNECT_URL = "http://127.0.0.1:8765"
DEFAULT_GEMINI_MODEL = "gemini-2.5-pro"
DEFAULT_OPENAI_COMPATIBLE_MODEL = "gemini-2.5-flash"


class PortableSetupError(RuntimeError):
    pass


@dataclass(frozen=True)
class RuntimePaths:
    root: Path
    scripts: Path
    config_local: Path
    runtime: Path
    runtime_env: Path
    venv: Path
    python: Path


def runtime_paths() -> RuntimePaths:
    venv = RUNTIME_DIR / ".venv"
    python = venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    return RuntimePaths(
        root=PROJECT_ROOT,
        scripts=PROJECT_ROOT / "scripts",
        config_local=CONFIG_LOCAL_DIR,
        runtime=RUNTIME_DIR,
        runtime_env=RUNTIME_ENV_FILE,
        venv=venv,
        python=python,
    )


def ensure_portable_directories() -> None:
    CONFIG_LOCAL_DIR.mkdir(parents=True, exist_ok=True)
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)


def project_python_search_order() -> list[Path]:
    paths = runtime_paths()
    candidates = [paths.python, Path(sys.executable)]
    return [candidate for candidate in candidates if candidate.exists()]


def require_supported_python() -> None:
    if sys.version_info < (3, 12):
        raise PortableSetupError(
            "Python 3.12 or newer is required. Please install Python 3.12+ and run this tool again."
        )


def read_pyproject_dependencies() -> list[str]:
    pyproject_path = PROJECT_ROOT / "pyproject.toml"
    if not pyproject_path.exists():
        return []

    try:
        import tomllib
    except ModuleNotFoundError as error:  # pragma: no cover - Python < 3.11 guard
        raise PortableSetupError("Could not read pyproject.toml with this Python.") from error

    payload = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    dependencies = payload.get("project", {}).get("dependencies", [])
    if not isinstance(dependencies, list):
        return []
    return [item for item in dependencies if isinstance(item, str) and item.strip()]


def run_command(command: list[str], cwd: Path = PROJECT_ROOT) -> None:
    printable = " ".join(command)
    print(f"[run] {printable}")
    subprocess.run(command, cwd=str(cwd), check=True)


def load_runtime_env(path: Path = RUNTIME_ENV_FILE) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition("=")
        if not separator:
            continue
        normalized_key = key.strip()
        if normalized_key:
            values[normalized_key] = value.strip()
    return values


def write_runtime_env(values: dict[str, str], path: Path = RUNTIME_ENV_FILE) -> None:
    lines = [
        "# Local runtime configuration generated by scripts/configure_environment.py",
        "# This file is machine-specific and intentionally ignored by git.",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def apply_runtime_env(values: dict[str, str]) -> None:
    for key, value in values.items():
        if value:
            os.environ[key] = value


def read_json_file(path: Path) -> dict[str, object]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def write_json_file(path: Path, payload: dict[str, object]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def parse_anki_connect_url(url: str) -> tuple[str, int]:
    from urllib.parse import urlparse

    parsed = urlparse(url.strip())
    if parsed.scheme not in {"http", "https"}:
        raise PortableSetupError("AnkiConnect URL must start with http:// or https://.")
    if not parsed.hostname:
        raise PortableSetupError("AnkiConnect URL must include a host.")
    if parsed.port is None:
        raise PortableSetupError("AnkiConnect URL must include a port, usually 8765.")
    return parsed.hostname, int(parsed.port)


def format_path(path: Path) -> str:
    return str(path.resolve())


def print_header(title: str) -> None:
    print()
    print("=" * 72)
    print(title)
    print("=" * 72)


def print_key_values(items: Iterable[tuple[str, object]]) -> None:
    for key, value in items:
        print(f"{key}: {value}")


def platform_summary() -> dict[str, str]:
    return {
        "platform": platform.platform(),
        "python": sys.version.split()[0],
        "executable": sys.executable,
    }
